name: disable_web_context_menu
description: "Disables the web context menu for a given widget"
homepage: https://github.com/nank1ro/disable_web_context_menu
version: 1.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
